const express = require("express")
const app = express()
app.use(express.json())
app.use(require('cors')())
app.set('secret', '973hjkdhfkjh')
app.use('/updateImg', express.static(__dirname + '/updateImg'))
app.use('/updateHeroImg', express.static(__dirname + '/updateHeroImg'))
app.use('/updateHeroDesImg', express.static(__dirname + '/updateHeroDesImg'))
app.use('/multerFutext', express.static(__dirname + '/multerFutext'))
app.use('/multerAbs', express.static(__dirname + '/multerAbs'))
require('./routes/admin')(app)
require('./plugins/db')(app)
app.listen(3000, () => {
    console.log('http://localhost:3000')
})